idle=yes
keep-open=yes

slang=enGB,en-GB,en,eng,enUS,en-US,unknown
alang=enGB,en-GB,en,eng,enUS,en-US

sub-font-size=36
sub-color="#FFEBD834"

sub-border-style=background-box
sub-border-color="#FF262626"
sub-blur=5

sub-border-size=3

sub-shadow-offset=1
sub-shadow-color="#33000000"

sub-spacing=0.5

sub-ass-override=force

blend-subtitles
