from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from gi.repository import GLib  # pyright: ignore[reportMissingModuleSource]

import util
from hyprland_options import write_atomic
from util import BindableSettings, JsonSettings


POWER_VALUES_PATH = Path(
    os.path.expanduser("~/.local/share/ignis/hypridle.conf")
)


def _minutes(value: Any, fallback: int) -> int:
    try:
        return max(1, min(240, int(value)))
    except (TypeError, ValueError):
        return fallback


@JsonSettings("power")
class PowerSettings(BindableSettings):
    display_timeout_enabled: bool = True
    display_timeout_minutes: int = 10
    lock_timeout_enabled: bool = True
    lock_timeout_minutes: int = 15
    suspend_timeout_enabled: bool = True
    suspend_timeout_minutes: int = 30

    @staticmethod
    def migrate_settings(data: dict[str, Any]) -> dict[str, Any]:
        migrated = dict(data)
        migrated["display_timeout_enabled"] = bool(
            migrated.get("display_timeout_enabled", True)
        )
        migrated["display_timeout_minutes"] = _minutes(
            migrated.get("display_timeout_minutes", 10), 10
        )
        migrated["lock_timeout_enabled"] = bool(
            migrated.get("lock_timeout_enabled", True)
        )
        migrated["lock_timeout_minutes"] = _minutes(
            migrated.get("lock_timeout_minutes", 15), 15
        )
        migrated["suspend_timeout_enabled"] = bool(
            migrated.get("suspend_timeout_enabled", True)
        )
        migrated["suspend_timeout_minutes"] = _minutes(
            migrated.get("suspend_timeout_minutes", 30), 30
        )
        return migrated

    def set_display_timeout_enabled(self, value: bool) -> None:
        self.display_timeout_enabled = bool(value)
        self._schedule_restart()

    def set_display_timeout_minutes(self, value: int) -> None:
        self.display_timeout_minutes = _minutes(value, 10)
        self._schedule_restart()

    def set_lock_timeout_enabled(self, value: bool) -> None:
        self.lock_timeout_enabled = bool(value)
        self._schedule_restart()

    def set_lock_timeout_minutes(self, value: int) -> None:
        self.lock_timeout_minutes = _minutes(value, 15)
        self._schedule_restart()

    def set_suspend_timeout_enabled(self, value: bool) -> None:
        self.suspend_timeout_enabled = bool(value)
        self._schedule_restart()

    def set_suspend_timeout_minutes(self, value: int) -> None:
        self.suspend_timeout_minutes = _minutes(value, 30)
        self._schedule_restart()

    def sync(self) -> None:
        write_atomic(
            POWER_VALUES_PATH,
            "# Generated by Ignis Settings; values are seconds.\n"
            f"$display_timeout = {self.display_timeout_minutes * 60}\n"
            f"$display_condition = {'true' if self.display_timeout_enabled else 'false'}\n"
            f"$lock_timeout = {self.lock_timeout_minutes * 60}\n"
            f"$lock_condition = {'true' if self.lock_timeout_enabled else 'false'}\n"
            f"$suspend_timeout = {self.suspend_timeout_minutes * 60}\n"
            f"$suspend_condition = {'true' if self.suspend_timeout_enabled else 'false'}\n",
        )

    def _schedule_restart(self) -> None:
        source_id = getattr(self, "_restart_source_id", None)
        if source_id is not None:
            GLib.source_remove(source_id)

        def restart() -> bool:
            self._restart_source_id = None
            util.shell(
                "pkill -x hypridle; "
                "setsid hypridle >/dev/null 2>&1 &"
            )
            return False

        self._restart_source_id = GLib.timeout_add(500, restart)

    def restart(self) -> None:
        self._schedule_restart()


power_settings = PowerSettings()
