general {
  after_sleep_cmd = hyprctl dispatch dpms on && (pkill hyprpaper ; hyprctl dispatch exec hyprpaper)
}

# turn screen off after 3 minutes of inactivity
listener {
  timeout = 180
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# go to sleep after 15 minutes of inactivity
listener {
  timeout = 900
  on-timeout = systemctl suspend
}

