general {
  lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
  after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# turn screen off after 3 minutes of inactivity
listener {
  timeout = 180
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# go to sleep after 15 minutes of inactivity
listener {
  timeout = 900
  on-timeout = systemctl suspend
}

