general {
  lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
  after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# turn screen off after 5 minutes of inactivity
listener {
  timeout = 300
  on-timeout = ddcutil setvcp D6 04 && hyprctl dispatch dpms off
  on-resume = ddcutil setvcp D6 01 && hyprctl dispatch dpms on
}

# go to sleep after 30 minutes of inactivity
listener {
  timeout = 1800
  on-timeout = systemctl suspend
}

