# vim:ft=mconf
devices = {
  "name:k10temp" = cpu
  "name:it8689" = mobo
  "pci:03:00.0" = gpu
}

sensors = {
  cpu = {
    cpu = {
      readfile = temp1_input
    }
  }
}

curves = {
  regular = {
    type = step
    sensor = cpu
    points = [
      [0, 30],
      [60, 50],
      [70, 80],
      [100, 100]
    ]
    hysteresis = 0
    period = 2
  }

  max = {
    type = step
    sensor = cpu
    points = [
      [0, 100]
    ]
  }

  zero = {
    type = step
    sensor = cpu
    points = [
      [0, 0]
    ]
  }
}

$curve = $curve?regular

fans = {
  mobo = {
    cpu-fans = {
      curve = $curve 

      inputfile = pwm1 
      enablefile = pwm1_enable 
      readfile = fan1_input 
    }

    case-fans = {
      curve = $curve

      inputfile = pwm2
      enablefile = pwm2_enable
      readfile = fan2_input
    }
  }
}
