hl.config {
	autogenerated = 0,

	ecosystem = {
		no_update_news = true,
		no_donation_nag = true,
	},
}

local home = os.getenv("HOME")
local config = home .. "/.config/hypr"
local ignisData = home .. "/.local/share/ignis"

local function file_exists(path)
	local f = io.open(path, "r")

	if f then
		f:close()
		return true
	end

	return false
end

-- ┌──────────┐
-- │ SOURCES  │
-- └──────────┘

local monitors = ignisData .. "/monitors.lua"
if file_exists(monitors) then
	dofile(monitors)
end

local optsFp = ignisData .. "/opts.lua"
local opts = {}

if file_exists(optsFp) then
	opts = dofile(optsFp) or {}
end

-- ┌──────────┐
-- │ PROGRAMS │
-- └──────────┘

local programs = opts.programs or {}

local terminal = programs.terminal or "ghostty"
local fileManager = programs.fileManager or "nautilus --new-window"
local menu = programs.menu or "goignis open-window ignis_launcher_proxy"
local browser = programs.browser or "firefox"

hl.env("EDITOR", programs.editor or "nvim")

-- ┌───────────┐
-- │ AUTOSTART │
-- └───────────┘

local autostart = {
	"awww-daemon",
	"~/.config/hypr/scripts/set_curr_wallpaper.sh first-start",
	"goignis init",
	"wl-clip-persist --clipboard regular",
	"hypridle",
	"~/.config/hypr/scripts/autostart.sh",
	"/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1",
}

hl.on("hyprland.start", function()
	for _, cmd in ipairs(autostart) do
		hl.exec_cmd(cmd)
	end
end)

-- ┌──────────┐
-- │ ENV VARS │
-- └──────────┘

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("HOST_LC_ALL", "$LANG")

hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("DXVK_HDR", "1")
hl.env("ENABLE_HDR_WSI", "1")

-- ┌─────────────┐
-- │ CURSOR SIZE │
-- └─────────────┘

local cursorSize = 24

hl.env("XCURSOR_SIZE", tostring(cursorSize))
hl.env("HYPRCURSOR_SIZE", tostring(cursorSize))

hl.exec_cmd(("hyprctl setcursor Adwaita %d"):format(cursorSize))

-- ┌───────────────┐
-- │ LOOK AND FEEL │
-- └───────────────┘

hl.config {
	general = {
		gaps_in = 4,
		gaps_out = 8,

		border_size = 0,

		resize_on_border = false,

		allow_tearing = false,
	},

	decoration = {
		rounding = 12,
		rounding_power = 2,

		dim_inactive = true,
		dim_strength = 0.2,

		blur = {
			enabled = true,
			size = 3,
			passes = 3,

			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},

	misc = {
		force_default_wallpaper = 1,
		disable_hyprland_logo = true,
		background_color = "0x000000",
	},

	xwayland = {
		force_zero_scaling = true,
		use_nearest_neighbor = true,
	},

	master = {
		mfact = 0.60,
		new_status = "slave",
		allow_small_split = true,
	},

	dwindle = {
		preserve_split = true,
	},

	input = {
		kb_layout = "",
		kb_options = "fkeys:basic_13-24",

		follow_mouse = 1,

		touchpad = {
			natural_scroll = true,
		},
	},

	render = {
		cm_enabled = true,
	},
}

hl.curve("curve", {
	type = "bezier",

	points = {
		{ 0, 0.9 },
		{ 0.1, 1 },
	},
})

local speed = 2

hl.animation {
	leaf = "windows",

	enabled = true,
	speed = speed,

	bezier = "curve",
	style = "gnomed",
}

hl.animation {
	leaf = "workspaces",

	enabled = true,
	speed = speed,

	bezier = "curve",
	style = "slide",
}

-- ┌──────────┐
-- │ GESTURES │
-- └──────────┘

hl.gesture {
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
}

-- ┌──────────────┐
-- │ KEYBINDINGS  │
-- └──────────────┘

local keybindings = opts.keybindings or {}

local function binding(key, modifiers, primary_modifier)
	local selected_modifiers = {}
	for _, modifier in ipairs(modifiers or {}) do
		table.insert(selected_modifiers, modifier)
	end
	if primary_modifier == nil then
		primary_modifier = "SUPER"
	end
	if primary_modifier ~= "none" then
		table.insert(selected_modifiers, primary_modifier)
	end

	return {
		key = key,
		modifiers = selected_modifiers,
	}
end

local function bind(action, fallback, callback, options)
	local spec = keybindings[action] or fallback
	if not spec or spec.enabled == false or not spec.key or spec.key == "" then
		return
	end

	local parts = {}
	local added = {}
	local function add(value)
		if value and value ~= "" and not added[value] then
			table.insert(parts, value)
			added[value] = true
		end
	end

	for _, modifier in ipairs(spec.modifiers or {}) do
		add(modifier)
	end
	add(spec.key)
	hl.bind(table.concat(parts, " + "), callback, options)
end

-- apps
bind("close_window", binding("Q"), hl.dsp.window.close())
bind("open_file_manager", binding("F"), hl.dsp.exec_cmd(fileManager))
bind("open_terminal", binding("RETURN"), hl.dsp.exec_cmd(terminal))
bind("open_browser", binding("B"), hl.dsp.exec_cmd(browser))
bind("toggle_floating", binding("T"), hl.dsp.window.float())
bind("open_launcher", binding("SPACE"), hl.dsp.exec_cmd(menu))
local function toggle_layout_action()
	local layout = hl.get_config("general.layout")

	if layout == "master" then
		hl.dispatch(hl.dsp.layout("swapwithmaster master"))
	elseif layout == "dwindle" then
		hl.dispatch(hl.dsp.layout("togglesplit"))
	end
end
bind("toggle_layout", binding("S"), toggle_layout_action)

-- focus
bind("focus_left_h", binding("H"), hl.dsp.focus { direction = "left" })
bind("focus_down_j", binding("J"), hl.dsp.focus { direction = "down" })
bind("focus_up_k", binding("K"), hl.dsp.focus { direction = "up" })
bind("focus_right_l", binding("L"), hl.dsp.focus { direction = "right" })

bind("focus_left_arrow", binding("left"), hl.dsp.focus { direction = "left" })
bind("focus_down_arrow", binding("down"), hl.dsp.focus { direction = "down" })
bind("focus_up_arrow", binding("up"), hl.dsp.focus { direction = "up" })
bind("focus_right_arrow", binding("right"), hl.dsp.focus { direction = "right" })

-- move windows
bind("move_up_h", binding("H", { "SHIFT" }), hl.dsp.window.move { direction = "up" })
bind("move_down_j", binding("J", { "SHIFT" }), hl.dsp.window.move { direction = "down" })
bind("move_left_k", binding("K", { "SHIFT" }), hl.dsp.window.move { direction = "left" })
bind("move_right_l", binding("L", { "SHIFT" }), hl.dsp.window.move { direction = "right" })

bind("move_up_arrow", binding("left", { "SHIFT" }), hl.dsp.window.move { direction = "up" })
bind("move_down_arrow", binding("down", { "SHIFT" }), hl.dsp.window.move { direction = "down" })
bind("move_left_arrow", binding("up", { "SHIFT" }), hl.dsp.window.move { direction = "left" })
bind("move_right_arrow", binding("right", { "SHIFT" }), hl.dsp.window.move { direction = "right" })

bind("fullscreen", binding("F", { "SHIFT" }), hl.dsp.window.fullscreen())

-- keyboard layouts

bind("keyboard_layout", binding("SPACE", { "ALT" }, "none"), hl.dsp.exec_cmd("goignis open-window ignis_keyboard_layout_proxy"))

-- misc
bind("notifications", binding("N"), hl.dsp.exec_cmd("swaync-client -t"))

-- screenshots
bind("screenshot_area", binding("S", { "SHIFT" }), hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh area"))

bind("screenshot_window", binding("W", { "SHIFT" }), hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh window"))

bind("screenshot_monitor", binding("M", { "SHIFT" }), hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh monitor"))

bind("ocr", binding("T", { "SHIFT" }), hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-ocr.sh"))

bind("colour_picker", binding("C", { "SHIFT" }), hl.dsp.exec_cmd("hyprpicker -a"))

-- workspaces

local workspaces_span_displays = opts.workspaces_span_displays == true
local workspace_count = math.max(1, math.min(10, tonumber(opts.workspace_count) or 10))
local workspace_monitors = hl.get_monitors()
table.sort(workspace_monitors, function(a, b)
	return a.id < b.id
end)
local workspace_primary = nil

for _, monitor in ipairs(workspace_monitors) do
	if monitor.name == opts.primary_monitor then
		workspace_primary = monitor
		break
	end
end

workspace_primary = workspace_primary or workspace_monitors[1]

local workspace_offsets = {}
local next_workspace_block = 1
if workspace_primary then
	workspace_offsets[workspace_primary.name] = 0
	for _, monitor in ipairs(workspace_monitors) do
		if monitor.name ~= workspace_primary.name then
			workspace_offsets[monitor.name] = next_workspace_block * 10
			next_workspace_block = next_workspace_block + 1
		end
	end
end

local function logical_workspace_id(logical_id, monitor)
	return (workspace_offsets[monitor.name] or 0) + logical_id
end

local function monitor_is_vertical(monitor)
	local width = tonumber(monitor.width) or 0
	local height = tonumber(monitor.height) or 0
	local transform = tonumber(monitor.transform) or 0
	if transform % 2 == 1 then
		width, height = height, width
	end
	return height > width
end

local function add_workspace_rule(logical_id, monitor)
	local rule = {
		workspace = tostring(logical_workspace_id(logical_id, monitor)),
		monitor = monitor.name,
		persistent = true,
	}
	if opts.layout_type == "master" and monitor_is_vertical(monitor) then
		rule.layout_opts = {
			orientation = "top",
		}
	end
	hl.workspace_rule(rule)
end

if workspace_primary then
	for logical_id = 1, workspace_count do
		if workspaces_span_displays then
			for _, monitor in ipairs(workspace_monitors) do
				add_workspace_rule(logical_id, monitor)
			end
		else
			add_workspace_rule(logical_id, workspace_primary)
		end
	end

	if not workspaces_span_displays then
		for _, monitor in ipairs(workspace_monitors) do
			if monitor.name ~= workspace_primary.name then
				add_workspace_rule(1, monitor)
			end
		end
	end
end

local workspace_command = "python3 " .. config .. "/scripts/logical-workspace.py"

for i = 1, workspace_count do
	local key = i == 10 and "0" or tostring(i)

	bind(
		"workspace_" .. i,
		binding(key),
		hl.dsp.exec_cmd(workspace_command .. " switch " .. tostring(i))
	)
	bind(
		"move_to_workspace_" .. i,
		binding(key, { "SHIFT" }),
		hl.dsp.exec_cmd(workspace_command .. " move " .. tostring(i))
	)
end

-- monitor focus
for _, monitor in ipairs(hl.get_monitors()) do
	local key = monitor.id + 1
	local default_key = key == 10 and "0" or tostring(key)

	bind(
		"focus_monitor_" .. key,
		binding(default_key, {}, "ALT"),
		hl.dsp.focus { monitor = monitor.name }
	)

	bind(
		"move_to_monitor_" .. key,
		binding(default_key, { "SHIFT" }, "ALT"),
		hl.dsp.window.move { monitor = monitor.name, follow = true }
	)
end

-- mouse
bind("drag_window", binding("mouse:272"), hl.dsp.window.drag(), { mouse = true })

bind("resize_window", binding("mouse:273"), hl.dsp.window.resize(), { mouse = true })

-- audio
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh inc_volume 2"), { repeating = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh dec_volume 2"), { repeating = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh toggle_mute_volume"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh play_pause"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh pause"))

hl.bind("XF86MediaPlayPause", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh play_pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh previous"))

-- brightness
bind("brightness_up", binding("XF86MonBrightnessUp", {}, "none"), hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true })

bind("brightness_down", binding("XF86MonBrightnessDown", {}, "none"), hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })

-- ┌──────────────────────────┐
-- │ WINDOW & WORKSPACE RULES │
-- └──────────────────────────┘

local function wr(match, props)
	local spec = {
		match = match,
	}

	for k, v in pairs(props) do
		spec[k] = v
	end

	hl.window_rule(spec)
end

wr({ class = ".*" }, {
	name = "suppress-maximise",
	suppress_event = "maximize",
})

wr({ class = "org.gnome.Calculator" }, {
	float = true,
})

wr({ class = "blueberry.py" }, {
	float = true,
})

wr({ class = "org.pulseaudio.pavucontrol" }, {
	float = true,
	size = "762 666",
})

wr({ class = ".*zenity.*" }, {
	float = true,
})

wr({ fullscreen = true }, {
	idle_inhibit = "fullscreen",
})

wr({ fullscreen_state_client = 2 }, {
	no_dim = true,
})

wr({ title = "Picture-in-Picture" }, {
	no_dim = true,
})

wr({ title = "Picture-in-picture" }, {
	no_dim = true,
})

wr({ class = ".*gimp.*" }, {
	no_dim = true,
})

hl.layer_rule {
	match = {
		namespace = "^(ignis_bar.*)$",
	},

	blur = true,
}

hl.layer_rule {
	match = {
		namespace = "^(ignis.*)$",
	},

	no_anim = true,
}

package.path = package.path .. ";" .. home .. "/.local/share/ignis/?.lua"
local ignisConfig = os.getenv("HOME") .. "/.local/share/ignis/ignis-hyprland.lua"
if file_exists(ignisConfig) then
	require("ignis-hyprland")
end
local hyprlandCustom = config .. "/hyprland-custom.lua"
if file_exists(hyprlandCustom) then
	require("hyprland-custom")
end

hl.on("hyprland.start", function()
  hl.exec_cmd("hyprpm reload")
end)
