background {
  monitor=
  blur_passes=1
  blur_size=7
  brightness=0.4
  path=~/.wallpapers/.wallpaper
}

input-field {
  monitor=
  size=300,35
  position=0, -48
  valign=center
  halign=center

  dots_center=false
  dots_size=0.200000
  dots_spacing=0.350000

  hide_input=false

  rounding=12

  font_family=Cantarell

  font_color=rgb(250, 250, 251)
  inner_color=rgba(41, 41, 41, 0.8)
  outer_color=rgba(82, 82, 82, 0.8)
  check_color=rgba(53, 132, 228, 0.8)
  fail_color=rgba(192, 28, 40, 0.8)
  placeholder_text=<span foreground="##B7B7BA"></span>
  fail_text=<b>$FAIL</b>

  fade_on_empty=false
  outline_thickness=2
}

label {
  monitor=
  color=rgb(255, 255, 255)
  font_family=Cantarell Bold
  font_size=48
  halign=center
  valign=center
  position=0, 32
  text=$TIME
}
