general {
  # lock_cmd = goignis list-windows | grep ignis_lockscreen || goignis open-window ignis_lock_proxy
  # before_sleep_cmd = loginctl lock-session
}

listener {
  timeout = 900
  on-timeout = hyprctl dispactch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
