general {
  lock_cmd = goignis list-windows | grep ignis_lockscreen || goignis open-window ignis_lock_proxy
  before_sleep_cmd = loginctl lock-session
}

listener {
  timeout = 900
  on-timeout = loginctl lock-session
}

listener {
  timeout = 1800
  on-timeout = systemctl suspend
}
