source = ~/.local/share/ignis/hypridle.conf

general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  timeout = $display_timeout
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
  condition_cmd = $display_condition
}

listener {
  timeout = $lock_timeout
  on-timeout = loginctl lock-session
  condition_cmd = $lock_condition
}

listener {
  timeout = $suspend_timeout
  on-timeout = systemctl suspend
  condition_cmd = $suspend_condition
}
