hl.config({
  autogenerated = 0,

  ecosystem = {
    no_update_news = true,
    no_donation_nag = true,
  },
})

local home = os.getenv("HOME")
local config = home .. "/.config/hypr"

local function file_exists(path)
  local f = io.open(path, "r")

  if f then
    f:close()
    return true
  end

  return false
end

-- ┌──────────┐
-- │ SOURCES  │
-- └──────────┘

local monitors = config .. "/monitors.lua"
if file_exists(monitors) then
  require("monitors")
end

local workspaces = config .. "/workspaces.lua"
if file_exists(workspaces) then
  require("workspaces")
end

local programsCustom = config .. "/programs-custom.lua"
local programs = {}

if file_exists(programsCustom) then
  programs = require("programs-custom")
end

-- ┌──────────┐
-- │ PROGRAMS │
-- └──────────┘

local terminal = programs.terminal or "ghostty"
local fileManager = programs.fileManager or "nautilus --new-window"
local menu = programs.menu or "goignis open-window ignis_launcher_proxy"
local browser = programs.browser or "firefox"

hl.env("EDITOR", programs.editor or "nvim")

-- ┌───────────┐
-- │ AUTOSTART │
-- └───────────┘

local autostart = {
  "awww-daemon",
  "~/.config/hypr/scripts/set_curr_wallpaper.sh first-start",
  "goignis init",
  "wl-clip-persist --clipboard regular",
  "hypridle",
  "~/.config/hypr/scripts/autostart.sh",
  "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1",
}

hl.on("hyprland.start", function ()
  for _, cmd in ipairs(autostart) do
    hl.exec_cmd(cmd)
  end
end
)

-- ┌──────────┐
-- │ ENV VARS │
-- └──────────┘

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("HOST_LC_ALL", "$LANG")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("DXVK_HDR", "1")
hl.env("ENABLE_HDR_WSI", "1")

-- ┌─────────────┐
-- │ CURSOR SIZE │
-- └─────────────┘

local cursorSize = 24

hl.env("XCURSOR_SIZE", tostring(cursorSize))
hl.env("HYPRCURSOR_SIZE", tostring(cursorSize))

hl.exec_cmd(("hyprctl setcursor Adwaita %d"):format(cursorSize))

-- ┌───────────────┐
-- │ LOOK AND FEEL │
-- └───────────────┘

hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 8,

    border_size = 0,

    resize_on_border = false,

    allow_tearing = false,
  },

  decoration = {
    rounding = 12,
    rounding_power = 2,

    dim_inactive = true,
    dim_strength = 0.2,

    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(24, 24, 24, 0.5)",
    },

    blur = {
      enabled = true,
      size = 3,
      passes = 3,

      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },

  misc = {
    force_default_wallpaper = 1,
    disable_hyprland_logo = true,
    background_color = "0x000000",
  },

  xwayland = {
    force_zero_scaling = true,
    use_nearest_neighbor = true,
  },

  master = {
    mfact = 0.60,
    new_status = "slave",
    allow_small_split = true,
  },

  dwindle = {
    preserve_split = true,
  },

  input = {
    kb_layout = "",
    kb_options = "fkeys:basic_13-24",

    follow_mouse = 1,

    touchpad = {
      natural_scroll = true,
    },
  },

  render = {
    direct_scanout = 1,
    cm_enabled = true,
  },
})

hl.curve("curve", {
  type = "bezier",

  points = {
    { 0, 0.9 },
    { 0.1, 1 },
  },
})

local speed = 2

hl.animation({
  leaf = "windows",

  enabled = true,
  speed = speed,

  bezier = "curve",
  style = "gnomed",
})

hl.animation({
  leaf = "workspaces",

  enabled = true,
  speed = speed,

  bezier = "curve",
  style = "slide",
})

-- ┌──────────┐
-- │ GESTURES │
-- └──────────┘

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})

-- ┌──────────────┐
-- │ KEYBINDINGS  │
-- └──────────────┘

local mod = "SUPER"

local function bind(keys, dispatcher, opts)
  hl.bind(keys, dispatcher, opts)
end

-- apps
bind(mod .. " + Q", hl.dsp.window.close())
bind(mod .. " + F", hl.dsp.exec_cmd(fileManager))
bind(mod .. " + RETURN", hl.dsp.exec_cmd(terminal))
bind(mod .. " + B", hl.dsp.exec_cmd(browser))
bind(mod .. " + T", hl.dsp.window.float())
bind(mod .. " + SPACE", hl.dsp.exec_cmd(menu))
bind(mod .. " + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/super_s.sh"))

-- focus
bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))
bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))

bind(mod .. " + left",  hl.dsp.focus({ direction = "left" }))
bind(mod .. " + down",  hl.dsp.focus({ direction = "down" }))
bind(mod .. " + up",    hl.dsp.focus({ direction = "up" }))
bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))

-- move windows
bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "up" }))
bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "left" }))
bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "up" }))
bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "left" }))
bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen())

-- screenshots
bind(
  mod .. " + SHIFT + S",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh area")
)

bind(
  mod .. " + SHIFT + W",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh window")
)

bind(
  mod .. " + SHIFT + M",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh monitor")
)

bind(
  mod .. " + SHIFT + T",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/hypr-ocr.sh")
)

bind(
  mod .. " + SHIFT + C",
  hl.dsp.exec_cmd("hyprpicker -a")
)

-- workspaces
for i = 1, 10 do
  local key = i == 10 and "0" or tostring(i)

  bind(mod .. " + " .. key, hl.dsp.focus({ workspace = tostring(i) }))

  bind(
    mod .. " + SHIFT + " .. key,
    hl.dsp.window.move({ workspace = tostring(i), follow=false })
  )
end

-- mouse
bind(
  mod .. " + mouse:272",
  hl.dsp.window.drag(),
  { drag = true }
)

bind(
  mod .. " + mouse:273",
  hl.dsp.window.resize(),
  { drag = true }
)

-- audio
bind(
  "XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh inc_volume 2"),
  { repeating = true }
)

bind(
  "XF86AudioLowerVolume",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh dec_volume 2"),
  { repeating = true }
)

bind(
  "XF86AudioMute",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh toggle_mute_volume")
)

bind(
  "XF86AudioPlay",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh play_pause")
)

bind(
  "XF86AudioPause",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh pause")
)

bind(
  "XF86MediaPlayPause",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh play_pause")
)

bind(
  "XF86AudioNext",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh next")
)

bind(
  "XF86AudioPrev",
  hl.dsp.exec_cmd("~/.config/hypr/scripts/audio.sh previous")
)

-- brightness
bind(
  "XF86MonBrightnessUp",
  hl.dsp.exec_cmd("brightnessctl set +5%"),
  { repeating = true }
)

bind(
  "XF86MonBrightnessDown",
  hl.dsp.exec_cmd("brightnessctl set 5%-"),
  { repeating = true }
)

-- ┌──────────────────────────┐
-- │ WINDOW & WORKSPACE RULES │
-- └──────────────────────────┘

local function wr(match, props)
  local spec = {
    match = match,
  }

  for k, v in pairs(props) do
    spec[k] = v
  end

  hl.window_rule(spec)
end

wr(
  { class = ".*" },
  {
    name = "suppress-maximise",
    suppress_event = "maximize",
  }
)

wr(
  { class = "org.gnome.Calculator" },
  {
    float = true,
  }
)

wr(
  { class = "blueberry.py" },
  {
    float = true,
  }
)

wr(
  { class = "org.pulseaudio.pavucontrol" },
  {
    float = true,
    size = "762 666",
  }
)

wr(
  { class = ".*zenity.*" },
  {
    float = true,
  }
)

wr(
  { fullscreen = true },
  {
    idle_inhibit = "fullscreen",
  }
)

wr(
  { fullscreen_state_client = 2 },
  {
    no_dim = true,
  }
)

wr(
  { title = "Picture-in-Picture" },
  {
    no_dim = true,
  }
)

wr(
  { title = "Picture-in-picture" },
  {
    no_dim = true,
  }
)

wr(
  { class = ".*gimp.*" },
  {
    no_dim = true,
  }
)

hl.layer_rule({
  match = {
    namespace = "^(ignis_bar.*)$",
  },

  blur = true,
})

hl.layer_rule({
  match = {
    namespace = "^(ignis.*)$",
  },

  no_anim = true,
})


package.path = package.path
  .. ";" .. home .. "/.local/share/ignis/?.lua"
local ignisConfig = os.getenv("HOME") .. "/.local/share/ignis/ignis-hyprland.lua"
if file_exists(ignisConfig) then
  require("ignis-hyprland")
end
local hyprlandCustom = config .. "/hyprland-custom.lua"
if file_exists(hyprlandCustom) then
  require("hyprland-custom")
end
