#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
SELECTED_REL="$1"

if [ -z "$SELECTED_REL" ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi
if [ ! -f "$SELECTED_REL" ]; then
    echo "File not found: $SELECTED_REL"
    exit 1
fi
SELECTED=$(readlink -f "$SELECTED_REL")

unlink $SCRIPT_DIR/wallpaper
ln -s "$SELECTED" $SCRIPT_DIR/wallpaper

pkill hyprpaper ; hyprctl dispatch exec hyprpaper

