#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
FILES=$(find $SCRIPT_DIR -maxdepth 1 -type f \( -iname "*.webp" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -printf "%f\n")

if [ -z "$FILES" ]; then
    echo "No image files found!"
    exit 1
fi

SELECTED=$(echo "$FILES" | rofi -dmenu -p "Select wallpaper")

if [ -z "$SELECTED" ]; then
    echo "No selection made!"
    exit 1
fi

unlink $SCRIPT_DIR/wallpaper
ln -s "$SELECTED" $SCRIPT_DIR/wallpaper

pkill hyprpaper ; hyprctl dispatch exec hyprpaper

