#!/bin/bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
SELECTED_REL="$1"

if [ -z "$SELECTED_REL" ]; then
  SELECTED_FILE=$(find "$SCRIPT_DIR" -type f \( -name "*.jpg" -o -name "*.png" \) -printf '%P\n' | fzf)
  SELECTED_REL="$SCRIPT_DIR/$SELECTED_FILE"
fi
if [ ! -f "$SELECTED_REL" ]; then
    echo "File not found: $SELECTED_REL"
    exit 1
fi
SELECTED=$(readlink -f "$SELECTED_REL")

unlink $SCRIPT_DIR/.wallpaper
ln -s "$SELECTED" $SCRIPT_DIR/.wallpaper

pkill hyprpaper ; hyprctl dispatch exec hyprpaper

