color0                #241f31
color1                #c01c28
color2                #2ec27e
color3                #f5c211
color4                #1e78e4
color5                #9841bb
color6                #0ab9dc
color7                #c0bfbc
color8                #5e5c64
color9                #ed333b
color10               #57e389
color11               #f8e45c
color12               #51a1ff
color13               #c061cb
color14               #4fd2fd
color15               #f6f5f4
background            #1e1e1e
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #1e1e1e
selection_background  #ffffff
selection_foreground  #5e5c64

opacity 0.95
background_opacity 0.95

symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

font_family      Cascadia Code
font_size        12.0

background_blur  1

